# Generated by Django 3.0.8 on 2020-07-08 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('shulde_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('shulde_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.Classe')),
            ],
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='FixePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('tot_amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.Admin')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.Classe')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shule.Faculty')),
                ('feetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.FeeType')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('shulde_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('sex', models.CharField(max_length=4)),
                ('age', models.CharField(max_length=10)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.Classe')),
                ('faculty', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shule.Faculty')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.Level')),
            ],
        ),
        migrations.AddField(
            model_name='shuleuser',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField()),
                ('amount', models.FloatField()),
                ('totfee', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.FixePayment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.RegisterStudent')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], max_length=3)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.Admin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('sex', models.CharField(max_length=4)),
                ('age', models.DateField()),
                ('email', models.CharField(blank=True, max_length=30)),
                ('phone', models.IntegerField()),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.EmployFunction')),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.Staff')),
            ],
        ),
        migrations.AddField(
            model_name='registerstudent',
            name='secretary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.Staff'),
        ),
        migrations.CreateModel(
            name='RapportCaisse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField()),
                ('debit', models.FloatField()),
                ('credit', models.FloatField()),
                ('balance', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cachier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField()),
                ('quantity', models.IntegerField()),
                ('unit_amount', models.FloatField()),
                ('tot_amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('shulde_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.Level')),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('sex', models.CharField(max_length=6)),
                ('age', models.CharField(max_length=10)),
                ('occupation', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('quater', models.CharField(max_length=50)),
                ('avenue', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shule.RegisterStudent')),
            ],
        ),
        migrations.AddField(
            model_name='fixepayment',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.Level'),
        ),
        migrations.AddField(
            model_name='fixepayment',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.Periode'),
        ),
        migrations.CreateModel(
            name='FixeEmployeeSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField()),
                ('amount', models.FloatField()),
                ('salary', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.RegistrationEmployee')),
                ('shulde_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField()),
                ('amount', models.FloatField()),
                ('tot_payment', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cachier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.Staff')),
                ('employee_salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.FixeEmployeeSalary')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.Classe')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.Faculty')),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.Staff')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.RegistrationEmployee')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='shulde_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.Level'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.State')),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='city',
            field=models.ForeignKey(blank=True, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='shule.City'),
        ),
        migrations.AddField(
            model_name='admin',
            name='country',
            field=models.ForeignKey(blank=True, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='shule.Country'),
        ),
        migrations.AddField(
            model_name='admin',
            name='state',
            field=models.ForeignKey(blank=True, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='shule.State'),
        ),
        migrations.AddField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
