# Generated by Django 3.0.8 on 2020-07-11 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shule', '0003_auto_20200711_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shule.Level'),
        ),
    ]
