# Generated by Django 3.0.8 on 2020-07-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shule', '0006_auto_20200714_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsell',
            name='secretary',
        ),
    ]
