# Generated by Django 3.0.8 on 2020-07-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shule', '0007_remove_productsell_secretary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsell',
            name='balance',
        ),
    ]
