# Generated by Django 3.0.8 on 2020-07-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shule', '0008_remove_productsell_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='payment',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='student',
            field=models.IntegerField(),
        ),
    ]
