# Generated by Django 3.0.8 on 2020-07-25 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shule', '0009_auto_20200720_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixeemployeesalary',
            name='shulde_admin',
        ),
    ]
