# Generated by Django 3.0.8 on 2020-07-25 02:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shule', '0010_remove_fixeemployeesalary_shulde_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixeemployeesalary',
            name='month',
            field=models.CharField(default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
    ]
